### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by j-pk** [kean/Nuke-Gifu-Plugin#4]
Podspec points to the Swift 3.0 version of Gifu, which introduces errors and warnings. Until Gifu is updated for Swift 4.0 officially, may want to point to `pod 'Gifu', :git => 'https://github.com/kaishin/Gifu.git', :branch => 'swift4'` in the podspec as Nuke supports Swift 4.0.

**Comment by kean** [comment]
Thanks, I'll investigate! I should probably switch back to `FLAnimatedImage` which seems to have an [active maintainer now](https://github.com/Flipboard/FLAnimatedImage/releases/tag/1.0.14). Give it a try maybe?

**Comment by j-pk** [comment]
I'd have to see how you implement it, but I just switched from FLAnimatedImage/SDWebImage to Nuke/Gifu in my personal project. However, if a project isn't being actively updated then that's a good sign to pivot to something that is.

**Comment by kean** [comment]
Tried that [Nuke/FLAnimatedImage](https://github.com/kean/Nuke-FLAnimatedImage-Plugin)?

**Comment by j-pk** [comment]
No, I haven't/didn't. When I switched I broke away completely from obj-c libraries.

**Comment by kean** [comment]
Update [Nuke FLAnimatedImage Plugin](https://github.com/kean/Nuke-FLAnimatedImage-Plugin) for Nuke 6 / Swift 4. Gifu still isn't officially updated to Swift 4.

**Comment by j-pk** [comment]
Gifu is now updated to Swift 4.

**Comment by kean** [comment]
Updated https://github.com/kean/Nuke-Gifu-Plugin/releases/tag/2.0
