### ISSUE TITLE
Xcode 9.3 Failed compiling Extension

### ISSUE THREAD

**Issue by swissdev** [kean/Nuke-Gifu-Plugin#7]
Hi

There is a problem while compiling the plugin with the latest Xcode version 9.3.
Two errors occurs in the subclass for AnimatedImage:

Overriding non-@objc declarations from extensions is not supported

and

'required' initializer 'init(imageLiteralResourceName:)' must be provided by subclass of 'UIImage'

Maybe there is a general bug for subclassing UIImage.

**Comment by francoiscilliers** [comment]
+1

**Comment by kean** [comment]
Hey @swissdev, @francoiscilliers! Thanks for raising this issue. I've pushed version 3.0 with a fix. See [release notes](https://github.com/kean/Nuke-Gifu-Plugin/releases/tag/3.0) for more info.

**Comment by zeshanmusawar** [comment]
How to Fix this issue . 
i have used the XCode 9.3 . But show this issue
  required convenience init(imageLiteralResourceName name: String) {
        fatalError("init(imageLiteralResourceName:) has not been implemented")
    }

**Comment by kean** [comment]
Hey, @zeshanmusawar. You no longer need to install this project to use Gifu plugin. Please remove NukeGifuPlugin dependency form your project and follow the instructions from README.
